# -*- coding: utf-8 -*-
"""검증된 full56 후보를 mouthnose STM32 펌웨어 자산으로 설치합니다.

기존 AI Generated/Assets를 백업하고, TFLite 재생성, ST Edge AI C 코드 생성, DSP 테이블/정규화/골든 벡터 헤더 작성, model_selection.json 갱신까지 수행합니다."""

from __future__ import annotations

import argparse
from datetime import datetime
import importlib.util
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

import numpy as np
import pandas as pd
from scipy import signal


SCRIPT_DIR = Path(__file__).resolve().parent
WORKSPACE_DIR = SCRIPT_DIR.parent
PROJECT_ROOT = WORKSPACE_DIR.parent
SOURCE_FEATURES_DIR = PROJECT_ROOT / "scripts" / "features"
if str(SOURCE_FEATURES_DIR) not in sys.path:
    sys.path.insert(0, str(SOURCE_FEATURES_DIR))
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import extract_features as ef  # noqa: E402
import stedgeai_utils  # noqa: E402


MOUTHNOSE_DIR = PROJECT_ROOT / "mouthnose"
FW_GENERATED_DIR = MOUTHNOSE_DIR / "Middlewares" / "ST" / "AI" / "Generated"
FW_ASSETS_DIR = MOUTHNOSE_DIR / "Middlewares" / "ST" / "AI" / "Assets"

FULL56_MODEL = WORKSPACE_DIR / "models" / "mlp_200ms_mfcc_delta.keras"
FULL56_FEATURES = WORKSPACE_DIR / "features" / "features_200ms_mfcc_delta.csv"
FULL56_METRICS = WORKSPACE_DIR / "reports" / "mlp_200ms_mfcc_delta_metrics.json"
FULL56_CANDIDATE_DIR = WORKSPACE_DIR / "stm32_candidate" / "full56"
FULL56_TFLITE = FULL56_CANDIDATE_DIR / "model" / "mlp_200ms_mfcc_delta_full56.tflite"

SAMPLE_RATE = 16000
FRAME_SIZE = 3200
HOP_SIZE = 2400
FFT_SIZE = 4096
BPF_LOW_HZ = 50.0
BPF_HIGH_HZ = 2500.0
BPF_ORDER = 4
NUM_MELS = 26
NUM_MFCC = 13
MFCC_FMIN_HZ = 50.0
MFCC_FMAX_HZ = 4000.0
ROLLOFF_RATIO = 0.85
EPS = 1.0e-12
WINDOW_TYPE = "hann"
DELTA_WIDTH = 2
DELTA_LOOKAHEAD_FRAMES = DELTA_WIDTH * 2
DELTA_LOOKAHEAD_MS = int(round((HOP_SIZE / SAMPLE_RATE) * 1000.0 * DELTA_LOOKAHEAD_FRAMES))


def configure_stdio() -> None:
    """설치 로그와 백업 경로가 UTF-8로 보이도록 표준 스트림을 설정합니다."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except Exception:
            pass


def timestamp() -> str:
    """백업/생성 폴더명에 사용할 현재 시각 문자열을 만듭니다."""
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def read_json(path: Path) -> dict:
    """full56 metrics나 manifest JSON을 UTF-8 dict로 읽습니다."""
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, payload: dict) -> None:
    """model_selection 및 설치 요약 JSON을 UTF-8 pretty format으로 저장합니다."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)


def c_string(value: object) -> str:
    """Python 값을 C 문자열 리터럴로 안전하게 이스케이프합니다."""
    text = str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_float(value: object) -> str:
    """Python float을 STM32 C 헤더에 넣을 수 있는 float 리터럴로 변환합니다."""
    number = float(value)
    if not np.isfinite(number):
        raise ValueError(f"cannot export non-finite float: {number}")
    text = f"{number:.9g}"
    if "e" not in text.lower() and "." not in text:
        text += ".0"
    return f"{text}f"


def chunked(values: list[str], per_line: int) -> str:
    """C 배열 초기화 값을 줄 단위로 나눠 사람이 읽기 좋게 만듭니다."""
    return ",\n".join(
        "    " + ", ".join(values[start : start + per_line])
        for start in range(0, len(values), per_line)
    )


def c_string_array(name: str, values: list[object]) -> str:
    """라벨명/feature명 같은 문자열 목록을 C static 배열 선언으로 만듭니다."""
    return f"static const char *const {name}[{len(values)}] = {{\n{chunked([c_string(v) for v in values], 4)}\n}};\n"


def c_float_array(name: str, values: np.ndarray, per_line: int = 6) -> str:
    """1차원 float 배열을 C static const float 초기화 코드로 만듭니다."""
    flat = np.asarray(values, dtype=np.float32).reshape(-1)
    return f"static const float {name}[{flat.size}] = {{\n{chunked([c_float(v) for v in flat], per_line)}\n}};\n"


def c_float_matrix(name: str, values: np.ndarray, per_line: int = 6) -> str:
    """2차원 float 행렬을 C static const float 초기화 코드로 만듭니다."""
    array = np.asarray(values, dtype=np.float32)
    rows = []
    for row in array:
        rows.append("  {\n" + chunked([c_float(v) for v in row], per_line) + "\n  }")
    return f"static const float {name}[{array.shape[0]}][{array.shape[1]}] = {{\n" + ",\n".join(rows) + "\n};\n"


def c_u8_array(name: str, values: np.ndarray, per_line: int = 12) -> str:
    """정수 인덱스 배열을 C static const uint8_t 초기화 코드로 만듭니다."""
    flat = np.asarray(values, dtype=np.uint8).reshape(-1)
    return f"static const uint8_t {name}[{flat.size}] = {{\n{chunked([str(int(v)) for v in flat], per_line)}\n}};\n"


def header_preamble(guard: str, description: str) -> str:
    """자동 생성 C 헤더의 include guard와 공통 include를 시작합니다."""
    return "\n".join(
        [
            "/* Auto-generated by full56_pipeline/scripts/install_full56_firmware_candidate.py. */",
            f"/* {description} */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "",
        ]
    )


def header_end(guard: str) -> str:
    """자동 생성 C 헤더의 include guard를 닫습니다."""
    return f"\n#endif /* {guard} */\n"


def load_keras_model(tf):
    """설치 기준 Keras full56 모델이 존재하는지 확인하고 로드합니다."""
    if not FULL56_MODEL.exists():
        raise FileNotFoundError(f"missing Keras model: {FULL56_MODEL}")
    return tf.keras.models.load_model(FULL56_MODEL)


def export_tflite(tf, model) -> dict:
    """Keras 모델을 설치 기준 TFLite 파일로 다시 변환하고 크기를 기록합니다."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    FULL56_TFLITE.parent.mkdir(parents=True, exist_ok=True)
    FULL56_TFLITE.write_bytes(converter.convert())
    return {"path": str(FULL56_TFLITE), "size_bytes": int(FULL56_TFLITE.stat().st_size)}


def tflite_predict(tf, features: np.ndarray) -> np.ndarray:
    """설치 기준 TFLite 모델을 여러 feature 행에 대해 실행해 확률 행렬을 반환합니다."""
    interpreter = tf.lite.Interpreter(model_content=FULL56_TFLITE.read_bytes())
    interpreter.allocate_tensors()
    input_detail = interpreter.get_input_details()[0]
    output_detail = interpreter.get_output_details()[0]
    outputs = []
    for row in np.asarray(features, dtype=np.float32):
        interpreter.set_tensor(input_detail["index"], row.reshape(input_detail["shape"]).astype(input_detail["dtype"]))
        interpreter.invoke()
        outputs.append(interpreter.get_tensor(output_detail["index"]).reshape(-1).astype(np.float32))
    return np.asarray(outputs, dtype=np.float32)


def evaluate_tflite(tf, feature_columns: list[str], labels: list[str]) -> dict:
    """설치 직전 TFLite가 테스트 CSV에서 기대 정확도를 유지하는지 재검증합니다."""
    df = pd.read_csv(FULL56_FEATURES)
    test_df = df[df["split"].astype(str) == "test"].copy()
    x_test = test_df[feature_columns].replace([np.inf, -np.inf], np.nan).fillna(0.0).to_numpy(dtype=np.float32)
    probs = tflite_predict(tf, x_test)
    pred_indices = np.argmax(probs, axis=1)
    pred_labels = [labels[int(i)] for i in pred_indices]
    accuracy = float(np.mean(test_df["label"].astype(str).to_numpy() == np.asarray(pred_labels, dtype=object)))

    pred_out = FULL56_CANDIDATE_DIR / "reports" / "full56_tflite_frame_predictions.csv"
    pred_out.parent.mkdir(parents=True, exist_ok=True)
    out_df = test_df[["file", "path", "label", "source_label", "breath_active"]].copy()
    out_df["pred_label"] = pred_labels
    out_df["pred_prob"] = np.max(probs, axis=1)
    out_df.to_csv(pred_out, index=False, encoding="utf-8")
    return {"frame_accuracy": accuracy, "predictions_csv": str(pred_out)}


def normalization_stats(model, feature_count: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Keras Normalization 레이어의 mean/variance/inv_std를 펌웨어 헤더용 배열로 추출합니다."""
    layer = model.get_layer("feature_normalization")
    weights = layer.get_weights()
    if len(weights) < 2:
        raise RuntimeError("feature_normalization layer has no mean/variance weights")
    mean = np.asarray(weights[0], dtype=np.float32).reshape(-1)
    variance = np.asarray(weights[1], dtype=np.float32).reshape(-1)
    if mean.size != feature_count or variance.size != feature_count:
        raise ValueError(f"normalization size mismatch: {mean.size}/{variance.size} vs {feature_count}")
    inv_std = 1.0 / np.sqrt(variance + 1.0e-7)
    return mean, variance, inv_std.astype(np.float32)


def run_stedgeai(network_name: str) -> dict:
    """production 네트워크명으로 ST Edge AI C 코드를 재생성하고 manifest를 저장합니다."""
    tool = stedgeai_utils.resolve_stedgeai_tool(None)
    run_id = timestamp()
    run_dir = FULL56_CANDIDATE_DIR / "stedgeai_runs" / f"run_{run_id}_{network_name}"
    output_dir = run_dir / "stedgeai_output"
    workspace_dir = run_dir / "workspace"
    output_dir.mkdir(parents=True, exist_ok=True)
    workspace_dir.mkdir(parents=True, exist_ok=True)
    temp_root = Path(tempfile.gettempdir()) / "stm32_breath_full56_install" / f"run_{run_id}_{network_name}"
    temp_model_dir = temp_root / "model"
    temp_output_dir = temp_root / "output"
    temp_workspace_dir = temp_root / "workspace"
    temp_model_dir.mkdir(parents=True, exist_ok=True)
    temp_output_dir.mkdir(parents=True, exist_ok=True)
    temp_workspace_dir.mkdir(parents=True, exist_ok=True)
    staged_model = temp_model_dir / FULL56_TFLITE.name
    shutil.copy2(FULL56_TFLITE, staged_model)
    command = [
        tool,
        "generate",
        "-m",
        str(staged_model),
        "--target",
        "stm32f4",
        "--type",
        "tflite",
        "--name",
        network_name,
        "--output",
        str(temp_output_dir),
        "--workspace",
        str(temp_workspace_dir),
        "--verbosity",
        "1",
    ]
    completed = subprocess.run(
        command,
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    (run_dir / "stedgeai_stdout.txt").write_text(completed.stdout, encoding="utf-8")
    (run_dir / "stedgeai_stderr.txt").write_text(completed.stderr, encoding="utf-8")
    if temp_output_dir.exists():
        shutil.copytree(temp_output_dir, output_dir, dirs_exist_ok=True)
    manifest = {
        "status": "ok" if completed.returncode == 0 else "failed",
        "returncode": int(completed.returncode),
        "run_id": run_id,
        "run_dir": str(run_dir),
        "stedgeai_output_dir": str(output_dir),
        "network_name": network_name,
        "command_text": subprocess.list2cmdline(command),
        "stdout_tail": completed.stdout[-4000:],
        "stderr_tail": completed.stderr[-4000:],
        "generated_files": sorted(p.name for p in output_dir.glob("*") if p.is_file()),
    }
    write_json(run_dir / "stedgeai_full56_install_summary.json", manifest)
    write_json(FULL56_CANDIDATE_DIR / "latest_stedgeai_breath_mlp_summary.json", manifest)
    if completed.returncode != 0:
        raise RuntimeError(manifest["stderr_tail"] or manifest["stdout_tail"])
    return manifest


def backup_current_firmware_assets() -> Path:
    """기존 mouthnose AI Generated/Assets를 timestamp 백업 폴더에 복사합니다."""
    backup_dir = PROJECT_ROOT / "backups" / "firmware_assets" / f"before_full56_install_{timestamp()}"
    backup_dir.mkdir(parents=True, exist_ok=False)
    shutil.copytree(FW_GENERATED_DIR, backup_dir / "Generated")
    shutil.copytree(FW_ASSETS_DIR, backup_dir / "Assets")
    (backup_dir / "README.md").write_text(
        "# 펌웨어 자산 백업\n\n"
        "full56 자산을 다시 설치하기 직전의 STM32Cube.AI 생성 파일과 헤더를 보존합니다. "
        "복원하려면 `Generated`와 `Assets`를 `mouthnose/Middlewares/ST/AI/` 아래로 "
        "다시 복사하십시오.\n",
        encoding="utf-8",
        newline="\n",
    )
    return backup_dir


def install_generated_files(output_dir: Path) -> None:
    """ST Edge AI가 생성한 breath_mlp C/H 파일들을 펌웨어 Generated 폴더로 복사합니다."""
    required = [
        "breath_mlp.c",
        "breath_mlp.h",
        "breath_mlp_config.h",
        "breath_mlp_data.c",
        "breath_mlp_data.h",
        "breath_mlp_data_params.c",
        "breath_mlp_data_params.h",
    ]
    missing = [name for name in required if not (output_dir / name).exists()]
    if missing:
        raise FileNotFoundError(f"missing ST Edge AI generated files: {missing}")
    for name in required:
        shutil.copy2(output_dir / name, FW_GENERATED_DIR / name)
    for extra in ("breath_mlp_c_info.json", "breath_mlp_generate_report.txt", "LICENSE.txt"):
        if (output_dir / extra).exists():
            shutil.copy2(output_dir / extra, FW_GENERATED_DIR / extra)


def write_config_header(path: Path, metrics: dict, tflite_info: dict, tflite_eval: dict, model) -> None:
    """라벨, feature 순서, 정규화 통계, DSP 상수를 breath_ai_config.h로 작성합니다."""
    labels = list(metrics["labels"])
    features = list(metrics["feature_columns"])
    mean, variance, inv_std = normalization_stats(model, len(features))
    lines = [
        header_preamble("BREATH_AI_CONFIG_H", "Full56 model labels, feature order, and DSP constants."),
        f"#define BREATH_AI_SAMPLE_RATE {SAMPLE_RATE}",
        f"#define BREATH_AI_FRAME_SIZE {FRAME_SIZE}",
        f"#define BREATH_AI_HOP_SIZE {HOP_SIZE}",
        f"#define BREATH_AI_FFT_SIZE {FFT_SIZE}",
        f"#define BREATH_AI_NUM_MELS {NUM_MELS}",
        f"#define BREATH_AI_NUM_MFCC {NUM_MFCC}",
        f"#define BREATH_AI_FEATURE_COUNT {len(features)}",
        f"#define BREATH_AI_LABEL_COUNT {len(labels)}",
        f"#define BREATH_AI_BPF_LOW_HZ {c_float(BPF_LOW_HZ)}",
        f"#define BREATH_AI_BPF_HIGH_HZ {c_float(BPF_HIGH_HZ)}",
        f"#define BREATH_AI_BPF_ORDER {BPF_ORDER}",
        f"#define BREATH_AI_ROLLOFF_RATIO {c_float(ROLLOFF_RATIO)}",
        f"#define BREATH_AI_EPS {c_float(EPS)}",
        f"#define BREATH_AI_MODEL_INPUT_DIMS {len(features)}",
        f"#define BREATH_AI_MODEL_OUTPUT_DIMS {len(labels)}",
        f"#define BREATH_AI_DELTA_WIDTH {DELTA_WIDTH}",
        f"#define BREATH_AI_DELTA_LOOKAHEAD_FRAMES {DELTA_LOOKAHEAD_FRAMES}",
        f"#define BREATH_AI_DELTA_LOOKAHEAD_MS {DELTA_LOOKAHEAD_MS}",
        f"#define BREATH_AI_TFLITE_SIZE_BYTES {int(tflite_info['size_bytes'])}",
        f"#define BREATH_AI_TFLITE_FRAME_ACCURACY {c_float(tflite_eval['frame_accuracy'])}",
        "#define BREATH_AI_INT8_FRAME_ACCURACY 0.0f",
        "#define BREATH_AI_GOLDEN_FILTER_TOLERANCE 1.0e-4f",
        "#define BREATH_AI_GOLDEN_FEATURE_TOLERANCE 1.0e-1f",
        "#define BREATH_AI_GOLDEN_MODEL_TOLERANCE 1.0e-4f",
        "",
        c_string_array("BREATH_AI_LABELS", labels),
        c_string_array("BREATH_AI_FEATURE_NAMES", features),
        c_float_array("BREATH_AI_NORM_MEAN", mean),
        c_float_array("BREATH_AI_NORM_VARIANCE", variance),
        c_float_array("BREATH_AI_NORM_INV_STD", inv_std),
        header_end("BREATH_AI_CONFIG_H"),
    ]
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def write_dsp_header(path: Path) -> None:
    """대역통과 SOS, Hann window, mel filterbank를 breath_dsp_tables.h로 작성합니다."""
    sos = ef.design_bandpass_filter(SAMPLE_RATE, BPF_LOW_HZ, BPF_HIGH_HZ, BPF_ORDER).astype(np.float32)
    window = signal.get_window(WINDOW_TYPE, FRAME_SIZE, fftbins=True).astype(np.float32)
    mel = ef.build_mel_filterbank(SAMPLE_RATE, FFT_SIZE, NUM_MELS, MFCC_FMIN_HZ, MFCC_FMAX_HZ).astype(np.float32)
    lines = [
        header_preamble("BREATH_DSP_TABLES_H", "Full56 causal DSP tables."),
        f"#define BREATH_DSP_SOS_SECTIONS {sos.shape[0]}",
        f"#define BREATH_DSP_SOS_COEFFS {sos.shape[1]}",
        f"#define BREATH_DSP_WINDOW_SIZE {window.shape[0]}",
        f"#define BREATH_DSP_NUM_MELS {mel.shape[0]}",
        f"#define BREATH_DSP_FFT_BINS {mel.shape[1]}",
        "",
        c_float_matrix("BREATH_DSP_FILTER_SOS", sos),
        c_float_array("BREATH_DSP_HANN_WINDOW", window),
        c_float_matrix("BREATH_DSP_MEL_FILTERBANK", mel),
        header_end("BREATH_DSP_TABLES_H"),
    ]
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def select_golden_rows(df: pd.DataFrame, labels: list[str], count_per_label: int = 2) -> pd.DataFrame:
    """STM32 self-test에 넣을 대표 테스트 feature 행을 라벨별로 선택합니다."""
    test_df = df[df["split"].astype(str) == "test"].copy()
    rows = []
    for label in labels:
        group = test_df[test_df["label"].astype(str) == label]
        if group.empty:
            group = df[df["label"].astype(str) == label]
        rows.append(group.head(count_per_label))
    return pd.concat(rows, ignore_index=True)


def write_golden_header(path: Path, metrics: dict, tf) -> None:
    """골든 feature와 TFLite 확률을 C 헤더로 저장해 펌웨어 self-test 기준값으로 씁니다."""
    labels = list(metrics["labels"])
    feature_columns = list(metrics["feature_columns"])
    df = pd.read_csv(FULL56_FEATURES)
    golden_df = select_golden_rows(df, labels, count_per_label=2)
    features = golden_df[feature_columns].replace([np.inf, -np.inf], np.nan).fillna(0.0).to_numpy(dtype=np.float32)
    probs = tflite_predict(tf, features)
    label_to_index = {label: index for index, label in enumerate(labels)}
    pred_indices = np.argmax(probs, axis=1).astype(np.uint8)

    lines = [
        header_preamble("BREATH_GOLDEN_VECTORS_H", "Full56 model-input golden vectors for STM32 self-test."),
        '#include "breath_ai_config.h"',
        "",
        f"#define BREATH_GOLDEN_VECTOR_COUNT {features.shape[0]}",
        f"#define BREATH_GOLDEN_FRAME_SIZE {FRAME_SIZE}",
        f"#define BREATH_GOLDEN_FEATURE_COUNT {features.shape[1]}",
        f"#define BREATH_GOLDEN_MODEL_OUTPUT_COUNT {len(labels)}",
        "#define BREATH_GOLDEN_HAS_MODEL_OUTPUTS 1",
        "",
        c_string_array("BREATH_GOLDEN_VECTOR_IDS", [f"full56_gv_{i:03d}" for i in range(features.shape[0])]),
        c_string_array("BREATH_GOLDEN_LABELS", golden_df["label"].astype(str).tolist()),
        c_string_array("BREATH_GOLDEN_SPLITS", golden_df["split"].astype(str).tolist()),
        c_string_array("BREATH_GOLDEN_FILES", golden_df["file"].astype(str).tolist()),
        c_u8_array("BREATH_GOLDEN_LABEL_INDEX", np.asarray([label_to_index[str(v)] for v in golden_df["label"]], dtype=np.uint8)),
        c_float_matrix("BREATH_GOLDEN_FEATURES", features),
        c_float_matrix("BREATH_GOLDEN_MLP_PROBS", probs),
        c_u8_array("BREATH_GOLDEN_MLP_PRED_LABEL_INDEX", pred_indices),
        c_float_array("BREATH_GOLDEN_MLP_PRED_PROB", np.max(probs, axis=1).astype(np.float32)),
        header_end("BREATH_GOLDEN_VECTORS_H"),
    ]
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def write_assets_readme(path: Path, metrics: dict) -> None:
    """설치된 AI Assets 폴더에 모델 구조와 지연 정보를 설명하는 README를 작성합니다."""
    text = f"""# STM32F407VET full56 AI 자산

`full56_pipeline/scripts/install_full56_firmware_candidate.py`가 생성합니다.

- 프레임: {FRAME_SIZE} samples = 16 kHz 기준 200 ms
- 홉: {HOP_SIZE} samples = 150 ms
- FFT: {FFT_SIZE}
- 특징 벡터: 56개 = static 17 + MFCC 13 + delta 13 + delta-delta 13
- Delta 문맥: MFCC 프레임 기준 전후 4칸, 약 {DELTA_LOOKAHEAD_MS} ms lookahead
- 모델: Tiny MLP {metrics.get("hidden_layers", [16, 8])}, float32 STM32Cube.AI network `breath_mlp`

자산 재설치 직전 백업은 `backups/firmware_assets/` 아래에 생성됩니다.
"""
    path.write_text(text, encoding="utf-8", newline="\n")


def write_model_selection(path: Path, metrics: dict, stedgeai: dict, tflite_info: dict, tflite_eval: dict, backup_dir: Path) -> None:
    """현재 설치된 모델, feature 수, ST Edge AI 실행 정보, 백업 위치를 JSON으로 남깁니다."""
    payload = {
        "status": "installed_full56_candidate",
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "selected_model": str(FULL56_MODEL),
        "selected_tflite": str(FULL56_TFLITE),
        "network_name": "breath_mlp",
        "feature_count": 56,
        "labels": metrics["labels"],
        "frame_size": FRAME_SIZE,
        "hop_size": HOP_SIZE,
        "fft_size": FFT_SIZE,
        "delta_width": DELTA_WIDTH,
        "delta_lookahead_frames": DELTA_LOOKAHEAD_FRAMES,
        "delta_lookahead_ms": DELTA_LOOKAHEAD_MS,
        "tflite_size_bytes": tflite_info["size_bytes"],
        "tflite_frame_accuracy": tflite_eval["frame_accuracy"],
        "stedgeai": stedgeai,
        "fallback_30feature_dir": str(backup_dir),
    }
    write_json(path, payload)


def main(argv: list[str] | None = None) -> int:
    """full56 후보 검증, 백업, C 코드/헤더 설치, 요약 저장을 한 번에 수행합니다."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--network-name", default="breath_mlp")
    parser.add_argument("--no-backup", action="store_true")
    args = parser.parse_args(argv)
    configure_stdio()

    import tensorflow as tf

    metrics = read_json(FULL56_METRICS)
    model = load_keras_model(tf)
    tflite_info = export_tflite(tf, model)
    tflite_eval = evaluate_tflite(tf, list(metrics["feature_columns"]), list(metrics["labels"]))
    stedgeai = run_stedgeai(args.network_name)

    backup_dir = PROJECT_ROOT / "backups" / "firmware_assets" / "not_created"
    if not args.no_backup:
        backup_dir = backup_current_firmware_assets()

    install_generated_files(Path(stedgeai["stedgeai_output_dir"]))
    write_config_header(FW_ASSETS_DIR / "breath_ai_config.h", metrics, tflite_info, tflite_eval, model)
    write_dsp_header(FW_ASSETS_DIR / "breath_dsp_tables.h")
    write_golden_header(FW_ASSETS_DIR / "breath_golden_vectors.h", metrics, tf)
    write_assets_readme(FW_ASSETS_DIR / "README.md", metrics)
    write_model_selection(FW_ASSETS_DIR / "model_selection.json", metrics, stedgeai, tflite_info, tflite_eval, backup_dir)

    summary = {
        "status": "ok",
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "firmware_generated_dir": str(FW_GENERATED_DIR),
        "firmware_assets_dir": str(FW_ASSETS_DIR),
        "fallback_30feature_dir": str(backup_dir),
        "feature_count": 56,
        "frame_size": FRAME_SIZE,
        "hop_size": HOP_SIZE,
        "fft_size": FFT_SIZE,
        "delta_lookahead_ms": DELTA_LOOKAHEAD_MS,
        "tflite": tflite_info,
        "tflite_eval": tflite_eval,
        "stedgeai": stedgeai,
    }
    write_json(FULL56_CANDIDATE_DIR / "installed_to_mouthnose_summary.json", summary)

    print("=== Full56 Firmware Candidate Installed ===")
    print(f"generated : {FW_GENERATED_DIR}")
    print(f"assets    : {FW_ASSETS_DIR}")
    print(f"fallback  : {backup_dir}")
    print(f"tflite acc: {tflite_eval['frame_accuracy'] * 100.0:.2f}%")
    print(f"delay     : {DELTA_LOOKAHEAD_MS} ms lookahead for exact delta2")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
